### ISSUE TITLE
Autocomplete background color

### ISSUE THREAD

**Issue by alekseideviatov** [SerafimArts/RoboticketLight#1]
![image](https://user-images.githubusercontent.com/2854588/61207339-88965100-a6fd-11e9-9d13-ee2ebdd7b5a2.png)

RoboticketLight version: 1.0.0
PHPStorm version: 2019.2 Beta (192.5728.26)

@SerafimArts, can you reproduce it in new version? Maybe you can suggest how fix it?

**Comment by SerafimArts** [comment]
Fixed https://github.com/SerafimArts/RoboticketLight/commit/eb179b0cef5793e304fe50c6fec9766507c80130

...and something else
