### ISSUE TITLE
Weak warnings style is strange

### ISSUE THREAD

**Issue by alekseideviatov** [SerafimArts/RoboticketLight#2]
Weak warnings highlighted very brightly.

![image](https://user-images.githubusercontent.com/2854588/61543775-ccb28a00-aa4c-11e9-94e1-86dc33e4ab5e.png)

In the same time, simple warnings haven't got underwaved selection
![image](https://user-images.githubusercontent.com/2854588/61545235-aa6e3b80-aa4f-11e9-87a7-8d96ba10b61e.png)

**Comment by SerafimArts** [comment]
Fixed since 1.1.2: 
- https://github.com/SerafimArts/RoboticketLight/releases/tag/1.1.2 
- https://plugins.jetbrains.com/plugin/12191-roboticket-light-theme/versions
