### ISSUE TITLE
Incompatible with latest 2019.3 IntelliJIDEA version

### ISSUE THREAD

**Issue by lensgolda** [SerafimArts/RoboticketLight#3]
<img width="409" alt="Снимок экрана 2019-12-02 в 18 28 45" src="https://user-images.githubusercontent.com/12370767/69976395-96743380-1531-11ea-84d1-2f7eac7da491.png">
<img width="635" alt="Снимок экрана 2019-12-02 в 18 29 21" src="https://user-images.githubusercontent.com/12370767/69976438-aa1f9a00-1531-11ea-931d-d4fff88a736d.png">

**Comment by SerafimArts** [comment]
Its very strange... The testing system showed that everything is fine
![image](https://user-images.githubusercontent.com/2461257/69993589-2d0a1a00-155d-11ea-92b5-19aaccfd4dbb.png)

Kk. Ill try to fix it. Sorry for waiting

**Comment by SerafimArts** [comment]
@lensgolda try to restart IDE. I think its a IDEA bug:
![image](https://user-images.githubusercontent.com/2461257/69994419-e74e5100-155e-11ea-91a3-e5faf4bdb70e.png)
![image](https://user-images.githubusercontent.com/2461257/69994460-fc2ae480-155e-11ea-94bd-ee61a4fa11cb.png)

**Comment by lensgolda** [comment]
thanks after being reinstalled and restarting IDEA, looks like it works fine. it was something strange, after installing first time, idea had some errors in event log. I suppose, possibly, because i have many plugins disabled manually. Anyway, it works, we can close the issue. Thanks for theme, looks good with Clojure code 👍

**Comment by SerafimArts** [comment]
Yep. I had the same problem. So this is an IDEA bug.

This seems to be this issue: https://youtrack.jetbrains.com/issue/IDEA-227821

**Comment by SerafimArts** [comment]
> Thanks for theme, looks good with Clojure code 👍

I checked only in Java, CSS, XML, JS and PHP languages. It is good that it is good for Clojure. Please inform if you dont like something in the color scheme or find a mistakes =)

**Comment by lensgolda** [comment]
Sure. Have an example. It's not mistake, but causes little discomfort with matched parentheses/braces highlighting in Clojure, which are little bit more important then in other languages. Compare this screenshots:
<img width="484" alt="Снимок экрана 2019-12-03 в 11 57 22" src="https://user-images.githubusercontent.com/12370767/70041154-4cd52880-15c5-11ea-8a45-916601172c05.png">
and this looks less contrasted, so parens/braces are hard to diff, especially when the current line is highlighted - in that case zero-contrasted.
<img width="496" alt="Снимок экрана 2019-12-03 в 11 58 43" src="https://user-images.githubusercontent.com/12370767/70041162-4e9eec00-15c5-11ea-9063-f1b522ab46d4.png">

**Comment by SerafimArts** [comment]
Useful note. Can you create a separate isssue for this?
