### ISSUE TITLE
Low contrast on matched parentheses/braces with Clojure code

### ISSUE THREAD

**Issue by lensgolda** [SerafimArts/RoboticketLight#4]
Sure. Have an example. It's not mistake, but causes little discomfort with matched parentheses/braces highlighting in Clojure, which are little bit more important then in other languages. Compare this screenshots:
<img width="484" alt="Снимок экрана 2019-12-03 в 11 57 22" src="https://user-images.githubusercontent.com/12370767/70041154-4cd52880-15c5-11ea-8a45-916601172c05.png">
and this looks less contrasted, so parens/braces are hard to diff, especially when the current line is highlighted - in that case zero-contrasted.
<img width="496" alt="Снимок экрана 2019-12-03 в 11 58 43" src="https://user-images.githubusercontent.com/12370767/70041162-4e9eec00-15c5-11ea-9063-f1b522ab46d4.png">

_Originally posted by @lensgolda in https://github.com/SerafimArts/RoboticketLight/issues/3#issuecomment-561097155_

**Comment by SerafimArts** [comment]
How much more convenient is this color/style?

![image](https://user-images.githubusercontent.com/2461257/70054337-6cca1380-15e8-11ea-8609-3e07bcfb13de.png)

**Comment by SerafimArts** [comment]
@lensgolda is this ok? 

[Roboticket Light.zip](https://github.com/SerafimArts/RoboticketLight/files/3916847/Roboticket.Light.zip)

Instructions:
1. Unzip
2. Export `*.icls` file

**Comment by lensgolda** [comment]
Just imported file, and 
<img width="623" alt="Снимок экрана 2019-12-03 в 15 59 38" src="https://user-images.githubusercontent.com/12370767/70057888-96823b00-15e6-11ea-80b8-19026f8bd3b6.png">
don's see any difference (restarted IDEA after import)

**Comment by SerafimArts** [comment]
There should appear a new choice in the selector (Editor -> Color Scheme -> Scheme). I think... But not sure))

**Comment by lensgolda** [comment]
it appears, i select it, then apply, then restart IDEA. And got the result above.

**Comment by SerafimArts** [comment]
kk. There is like this
![image](https://user-images.githubusercontent.com/2461257/70064040-e7e7f580-15f9-11ea-9c66-615620aa3dd7.png)

**Comment by lensgolda** [comment]
I think you misunderstood me ), i mean only matched parentheses and braces should be highlighted with contrast color to background. So you can leave all theme as is, and pick up only that background color (i check it, that exactly what we need ;) ) :

<img width="747" alt="Снимок экрана 2019-12-03 в 22 05 59" src="https://user-images.githubusercontent.com/12370767/70085834-b7b04f00-1619-11ea-9849-75de37af6b3a.png">

**Comment by SerafimArts** [comment]
Its looks like a IDEA bug (again) because in previous versions everything worked fine  :D

**Comment by SerafimArts** [comment]
Fixed, but there were other problems... https://youtrack.jetbrains.com/issue/WI-50069

**Comment by SerafimArts** [comment]
@lensgolda fixed. Please upgrade plugin. Is this ok?

**Comment by SerafimArts** [comment]
issue closed due to lack of feedback
